-- 코드를 입력하세요
# SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME FROM ANIMAL_INS ai JOIN ANIMAL_OUTS ao ON ai.ANIMAL_ID = ao.ANIMAL_ID WHERE ai.SEX_UPON_INTAKE LIKE "Intact%" and (ao.SEX_UPON_INTAKE LIKE "Spayed%" or ao.SEX_UPON_INTAKE LIKE "Neutered%");

SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME FROM ANIMAL_INS ai JOIN ANIMAL_OUTS ao ON ai.ANIMAL_ID = ao.ANIMAL_ID WHERE SEX_UPON_INTAKE LIKE "Intact%" and (SEX_UPON_OUTCOME LIKE "Spayed%" or SEX_UPON_OUTCOME LIKE "Neutered%");