-- 코드를 입력하세요
SELECT FLAVOR 
FROM (
    SELECT f.FLAVOR, (f.TOTAL_ORDER + j.TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF f JOIN JULY j ON f.FLAVOR = j.FLAVOR
) as subquery
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) desc LIMIT 3; 

# SELECT f.FLAVOR, (SUM(f.TOTAL_ORDER)) AS TOTAL_ORDER FROM FIRST_HALF f GROUP BY FLAVOR;
# SELECT f.FLAVOR, (SUM(f.TOTAL_ORDER)) AS TOTAL_ORDER FROM JULY f GROUP BY FLAVOR;