-- 코드를 작성해주세요
SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II
JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.ITEM_ID
WHERE IT.ITEM_ID 
    IN (SELECT ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID 
        IN
        (SELECT ITEM_ID FROM ITEM_INFO 
        WHERE RARITY = 'RARE'))
ORDER BY II.ITEM_ID desc;