-- 코드를 작성해주세요
WITH MAX_SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID FROM ECOLI_DATA E JOIN MAX_SIZE M ON YEAR(DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV;