-- 코드를 작성해주세요
select count(*) as FISH_COUNT
from FISH_INFO
where FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO where FISH_NAME = 'BASS') 
or FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO where FISH_NAME = 'SNAPPER');