# -- 코드를 작성해주세요
# SELECT i.ID, FISH_NAME, LENGTH FROM FISH_INFO i JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE WHERE LENGTH IN (
#     SELECT MAX(LENGTH) FROM FISH_INFO f GROUP BY f.FISH_TYPE
# )
# ORDER BY i.ID;

# WITH FISH AS (
#     SELECT ID, FISH_NAME, LENGTH FROM FISH_INFO i 
#     JOIN FISH_NAME_INFO n 
#     ON i.FISH_TYPE = n.FISH_TYPE
#     WHERE LENGTH IN (
#         SELECT MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE
#     ) and LENGTH is not null
#     ORDER BY ID
# )
# SELECT ID, FISH_NAME, LENGTH FROM FISH;

SELECT ID, FISH_NAME, LENGTH FROM FISH_INFO i JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE WHERE (i.FISH_TYPE,LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE
)
ORDER BY ID;